### PR TITLE
Remove update_aca_dark pieces

### PR DESCRIPTION
**Pull request by jeanconn**
Remove update_aca_dark.py and related pieces

### CODE REVIEW

**Comment by jeanconn** [comment]
I was just going to edit the cron task, but don't see a reason to keep the script either.

**Comment by jeanconn** [comment]
I could use a thumbs up or down on this now so I can cut 3.18 mica and make stuff to brief it for LR.

**Comment by jeanconn** [comment]
Thanks!

**Comment by jeanconn** [comment]
Though now I'm debating if I should install 3.18 on ska2 flight or just manually cut the cron task.

**Comment by taldcroft** [comment]
The truth is that you don't *need* to do any of this from my understanding.  As long as you do not manually install a new dark cal into /proj/sot/ska/data/aca_dark_cal then the mica code will do nothing.

**Comment by jeanconn** [comment]
Well, removing the entry in the task schedule in version control is a good idea (and is in here too) but the removing the rest of the module pieces is not required as you note.  Regarding 3.18 it was really a question on if we wanted the updated get_dark_cal_props_table to work in ska2 .

**Pull request merged**
