### PR TITLE
Use more idiomatic fetch and filter syntax

### PR DESCRIPTION
**Pull request by jeanconn**
Improve guide stats telem fetching and filtering per recommendation

### CODE REVIEW

**Comment by jeanconn** [comment]
Closes #142

**Comment by jeanconn** [comment]
Not sure what to do wrt to testing for this one, as I don't have any obsids handy that have bad data to confirm the updated filtering results are as-expected.

**Comment by taldcroft** [comment]
You can at least do a one-off by running this function standalone for any representative obsid and confirm the same results for the current and new code (by e.g. writing `eng_data` to a file).

**Comment by jeanconn** [comment]
I haven't written `eng_data` to a file, but I confirmed for obsid 17861 that the more idiomatic code filters out the same three rows of pcad0 data as the original code and that these rows have msids with bad status/quality.

**Pull request merged**
