### PR TITLE
Parse around all warning labels/severities in starcheck

### PR DESCRIPTION
**Pull request by jeanconn**
Parse around all warning labels/severities in starcheck

### CODE REVIEW

**Comment by jeanconn** [comment]
This doesn't do anything with the information, but seems not to break.  I have no good answer for how much testing this deserves.  I was half wondering about putting it in the release today to just cut down on mice releases.

**Comment by jeanconn** [comment]
I'll defer on this, because I think the 3.18 package needs to go now.

**Comment by jeanconn** [comment]
This cron task still runs on Ska 2.

**Comment by taldcroft** [comment]
OK.

**Comment by jeanconn** [comment]
These changes look to be part of the PR in https://github.com/sot/starcheck/pull/326 so can be closed here for now.

**Pull request closed without merging**
