### PR TITLE
Deprecate local mica versions of star probability functions 

### PR DESCRIPTION
**Pull request by taldcroft**
This is some untested code that I found lying in a branch on disk.  It's probably a good idea for cleanup.

### CODE REVIEW

**Comment by jeanconn** [comment]
I think this is fine, but I still have an action to review the docs and see if we've got any of the deprecated calls as examples (unlikely).

**Comment by taldcroft** [comment]
This is actually done already by different means.

**Comment by jeanconn** [comment]
Can you remind me about the means?

**Comment by taldcroft** [comment]
Well `mica.archive.aca_dark.dark_model` now consists of just 3 lines:
```
import warnings
warnings.warn("mica.archive.aca_dark.dark_model is deprecated.  See chandra_aca.dark_model", DeprecationWarning)
from chandra_aca.dark_model import *
```
So all of the code in this PR is irrelevant.  If there was code that was looking to mica for calculating star probabilities then it would have broken long ago.

**Pull request closed without merging**
