### PR TITLE
More centroid_dashboard tweaks

### PR DESCRIPTION
**Pull request by jeanconn**
## Description

A collection of fiddly little commits to: reduce extra processing, reduce skips or error-out observations, update page html to avoid reflows.

## Testing

- [x] Passes unit tests on linux
- [x] Functional testing

For functional testing, have just run a bunch of year 2020 with centroid dashboard code.  It is still filling in 

https://icxc.cfa.harvard.edu/aspect/centroid_reports

Fixes #

### CODE REVIEW

**Comment by jeanconn** [comment]
This isn't needed for shiny, I just had it lingering.

**Comment by taldcroft** [comment]
Excellent! One small request while you are at it is to change the y-axis label on the delta roll plot from `dr (arcsec)` to `Roll error (arcsec)` or (if that doesn't fit) `Roll err (arcsec)`.  `dr` is ambiguous.

**Comment by taldcroft** [comment]
Another feature request - CCD temperature. This could be put in the Roll error plot window as a right-side axis.

**Comment by taldcroft** [comment]
In the Performance details page, can you change Ending roll error to be "Not available" for ER's instead of 0.0? Not a huge deal but the 0.0 is wrong.

**Comment by taldcroft** [comment]
Can you put the Catalog and Visualization box on the right side in a 3rd column? This would optimize for modern wide screens and let me see nearly the entire page at once when flipping through.

**Comment by jeanconn** [comment]
I'm going to merge this and take those little RFEs and do them in a new PR.  Thanks @taldcroft !

**Pull request merged**
