### PR TITLE
Read and write guide and acq stats with tables3_api

### PR DESCRIPTION
**Pull request by jeanconn**
Read guide and acq stats with Py3-compat tables_open_file.

### CODE REVIEW

**Comment by jeanconn** [comment]
Closes #121 (to at least make *reading* the files Py3 compatible)

**Comment by taldcroft** [comment]
What about making a new module `tables3` that includes code like below in its `__init__.py` to monkey patch `tables`:
```
import tables
from distutils.version import LooseVersion

if LooseVersion(tables.__version__) < LooseVersion('3.0'):
    tables.open_file = tables.openFile
    ...
```
Then any code that needs to work with `tables` 2.x and 3.x can do so with:
```
import tables
import tables3  # inject small subset of tables 3.x API to tables

# Use the 3.x API
```
Eventually we will have migrated to Py3 with tables 3.x and the `import tables3` statements can be dropped.

**Comment by jeanconn** [comment]
Sure.  I thought we'd talked about monkey patching (and just patching) and decided to pass, but if you think this will reduce our maintenance headache, I'm good with it.

**Comment by jeanconn** [comment]
Also, do we just need this for open_file?  What about readWhere or others that I'm not immediately remembering?  readWhere would be a Table method and I'm not sure how deep you want to patch.

**Comment by taldcroft** [comment]
Well at least give it a try with the Table methods you can think of, starting with `readWhere`.

**Comment by jeanconn** [comment]
So far I've got readWhere, getWhereList, and readCoordinates

https://github.com/sot/tables3/pull/1/files

**Pull request merged**
