### PR TITLE
More mica.vv fixes for Py3

### PR DESCRIPTION
**Pull request by jeanconn**
More mica.vv fixes for Py3

### CODE REVIEW

**Comment by jeanconn** [comment]
This doesn't yet fix the test relative import problem, but at least more of the mica.vv. functions work.

**Comment by jeanconn** [comment]
I don't presently have a Py3 build area to install into to do great "installed module" tests, so I don't know if removing those relative imports fixes the test problem you noticed or not.

**Comment by taldcroft** [comment]
> I don't presently have a Py3 build area to install into to do great "installed module" tests, so I don't know if removing those relative imports fixes the test problem you noticed or not.

Not necessary!!  In the current setup, local testing is equivalent and so building one-off dev ska's for install-testing a single package is not really needed.  (Still useful for integration testing of course).  I noticed that issue with `python setup.py test`.

**Comment by jeanconn** [comment]
OK.  I had seen your `python setup.py test` but hadn't stored that information.  My `python setup.py test` seems to work OK now (after the other fixes) with the more absolute imports or the relative ones in the test module.  Which do you prefer?

**Comment by taldcroft** [comment]
You were just missing `__init__.py` in the `tests` directory so it didn't know it was a package.

Relative imports are preferred within bundled tests, that way you are guaranteed to be getting the right modules.  This is mostly just important in namespace packages where there is always the possibility of problems, but best to just make this standard practice always.

Fixed in c252b42, passing tests for me in ska flight, ska 3 and ska 2.18.

**Comment by jeanconn** [comment]
Well, not quite *missing* `__init__py` just not being good about checking for uncommitted files! :-)  That was another reason I couldn't reproduce your error.

Thanks!

**Comment by taldcroft** [comment]
Right, the dreaded uncommited file (or mistake in tarball creation setup) is one real use case for install-testing.  So in that case you can always do `python setup.py build` and change dir into the right spot in the build directory and do an `import package; package.test()`.

**Pull request merged**
