### PR TITLE
Add the list of obsids that are bad for trending to the project

### PR DESCRIPTION
**Pull request by jeanconn**
Add the list of obsids that are bad for trending to the project.

### CODE REVIEW

**Comment by jeanconn** [comment]
Not sure where this belongs, but this seems a better option than in the repo of starcheck data.

**Comment by jeanconn** [comment]
If we want this someplace else or broken into categories or accessible with a tool we should do this, otherwise not sure what to do with this PR.

**Comment by javierggt** [comment]
I'm ok with this. Remember I am adding a table to the agasc_supplement with OBSID info as well, but they are different things though.

**Comment by jeanconn** [comment]
What's that table with OBSID going to look like again?

**Review by taldcroft — APPROVED** [review]
LGTM.

**Comment by taldcroft** [comment]
Actually, what is missing is sphinx documentation that this file exists and description of its contents.

**Comment by jeanconn** [comment]
If we want this documented, can we merge #240 first?

**Comment by taldcroft** [comment]
> If we want this documented, can we merge #240 first?

Done.

**Comment by jeanconn** [comment]
I'm not sure how to test the docs anymore though:

```
shiny-fido$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.1.2
WARNING: html_static_path entry '_static' does not exist

Theme error:
no theme named 'bootstrap-ska' found (missing theme.conf?)
make: *** [html] Error 2
```

**Comment by taldcroft** [comment]
@javierggt ??

**Comment by javierggt** [comment]
ah, I just saw this. You can do:

```
python -m pip install git+https://github.com/sot/ska-sphinx-theme
```

**Comment by javierggt** [comment]
If you prefer to add the theme some other way, I can do that.

**Comment by jeanconn** [comment]
Thanks @javierggt!  Should the theme be in its own or another conda package in shiny?

**Comment by javierggt** [comment]
Whatever you prefer. I can add the meta.yaml in skare3.

**Comment by taldcroft** [comment]
If there is a new dependency for building Ska package docs then it should definitely be in Ska conda to allow building docs locally.

**Review by taldcroft — APPROVED** [review]

**Review by javierggt — APPROVED** [review]

**Pull request merged**
