### PR TITLE
Filter tracked guide star data for reasonable stats

### PR DESCRIPTION
**Pull request by jeanconn**
Filter the tracked data used to calculate the star residual stats to only include samples in NPNT, KALM, and while tracking GUID stars.

### CODE REVIEW

**Comment by jeanconn** [comment]
This closes #140

**Comment by jeanconn** [comment]
This change seems sane.  In a set of ~21000 stars with bogus dr_std values > 10, the change leaves  only ~120 stars with large dr_std values because something besides the target star was "legitimately" tracked during the nominal Kalman interval.

**Comment by taldcroft** [comment]
Looks good.  In perusing the code to make sure the MSID alignment was done correctly, I see some non-idiomatic code.  You can replace:
```
raw_eng_data = fetch.MSIDset(msids + slot_msids,
                             start_time,
                             stop_time,
                             filter_bad=False)
if not len(raw_eng_data['AOACASEQ']):
    raise ValueError("No telemetry for obsid {}".format(obsid))
eng_data = Table([raw_eng_data[col].vals for col in msids + slot_msids],
                 names=msids + slot_msids)
bads = np.column_stack([raw_eng_data[col].bads for col in msids + slot_msids])
eng_data['times'] = raw_eng_data['AOACASEQ'].times
eng_data['bad'] = np.any(bads == True, axis=1)
# limit the data to just good quality across all msids and double-check the times
eng_data = eng_data[~eng_data['bad']]
```
with
```
# Use short canonical names for values that are short-lived.
dat = fetch.MSIDset(msids + slot_msids,
                    start_time,
                    stop_time)
if len(dat['AOACASEQ']) == 0:  # say what you mean
    raise ValueError("No telemetry for obsid {}".format(obsid))
dat.interpolate(times=dat['AOACASEQ'].times, bad_union=True)
eng_data = Table([col.vals for col in dat.values()], names=dat.keys())
eng_data['times'] = dat.times
```
The `bad_union=True` option of `interpolate` is a powerful tool for [exactly this situation](http://cxc.cfa.harvard.edu/mta/ASPECT/tool_doc/eng_archive/fetch_tutorial.html#filtering-and-bad-values).  And don't forge that an `MSIDset` is an `OrderedDict`.

**Comment by jeanconn** [comment]
Gotcha.  I didn't actually know that you'd set fetch `interpolate` to take `times` so that's helpful.  I think this belongs in a different PR though.  Also there is plenty of non-idiomatic code in guide stats copied from acq stats.  Guide stats should also get an update to use the new centroid residual code when it is finally done.

**Comment by taldcroft** [comment]
Agreed on both points.

**Pull request merged**
